<?php
// auth-generated by ModuleConfigHandler
// date: 03/02/2020 12:32:19
define('MOD_FINANCE_ENABLED', true);
define('MOD_FINANCE_TITLE', 'finance LaiKeTui Module');
define('MOD_FINANCE_VERSION', 1.0);
define('MOD_FINANCE_NAME', 'finance');
define('MOD_FINANCE_AUTHOR', 'fly');
define('MOD_FINANCE_HOMEPAGE', null);
define('MOD_FINANCE_UPDATE_URL', null);
define('MOD_FINANCE_DESCRIPTION', 'finance LaiKeTui Module');
?>