<?php
// auth-generated by ModuleConfigHandler
// date: 03/03/2020 18:53:24
define('MOD_PRODUCT_ENABLED', true);
define('MOD_PRODUCT_TITLE', 'product LaiKeTui Module');
define('MOD_PRODUCT_VERSION', 1.0);
define('MOD_PRODUCT_NAME', 'product');
define('MOD_PRODUCT_AUTHOR', 'fly');
define('MOD_PRODUCT_HOMEPAGE', null);
define('MOD_PRODUCT_UPDATE_URL', null);
define('MOD_PRODUCT_DESCRIPTION', 'product LaiKeTui Module');
?>