<?php
// auth-generated by ModuleConfigHandler
// date: 03/02/2020 12:34:24
define('MOD_SYSTEM_ENABLED', true);
define('MOD_SYSTEM_TITLE', 'system LaiKeTui Module');
define('MOD_SYSTEM_VERSION', 1.0);
define('MOD_SYSTEM_NAME', 'system');
define('MOD_SYSTEM_AUTHOR', 'fly');
define('MOD_SYSTEM_HOMEPAGE', null);
define('MOD_SYSTEM_UPDATE_URL', null);
define('MOD_SYSTEM_DESCRIPTION', 'system LaiKeTui Module');
?>