<?php
// auth-generated by ModuleConfigHandler
// date: 03/02/2020 12:32:06
define('MOD_MEMBER_ENABLED', true);
define('MOD_MEMBER_TITLE', 'member LaiKeTui Module');
define('MOD_MEMBER_VERSION', 1.0);
define('MOD_MEMBER_NAME', 'member');
define('MOD_MEMBER_AUTHOR', 'fly');
define('MOD_MEMBER_HOMEPAGE', null);
define('MOD_MEMBER_UPDATE_URL', null);
define('MOD_MEMBER_DESCRIPTION', 'member LaiKeTui Module');
?>