<?php
// auth-generated by ModuleConfigHandler
// date: 03/02/2020 12:32:21
define('MOD_SCORE_ENABLED', true);
define('MOD_SCORE_TITLE', 'score LaiKeTui Module');
define('MOD_SCORE_VERSION', 1.0);
define('MOD_SCORE_NAME', 'score');
define('MOD_SCORE_AUTHOR', 'dhb');
define('MOD_SCORE_HOMEPAGE', null);
define('MOD_SCORE_UPDATE_URL', null);
define('MOD_SCORE_DESCRIPTION', 'score LaiKeTui Module');
?>