<?php
// auth-generated by ModuleConfigHandler
// date: 03/03/2020 18:40:08
define('MOD_API_ENABLED', true);
define('MOD_API_TITLE', 'api LaiKeTui Module');
define('MOD_API_VERSION', 1.0);
define('MOD_API_NAME', 'api');
define('MOD_API_AUTHOR', 'fly');
define('MOD_API_HOMEPAGE', null);
define('MOD_API_UPDATE_URL', null);
define('MOD_API_DESCRIPTION', 'api LaiKeTui Module');
?>