<?php
// auth-generated by ModuleConfigHandler
// date: 03/02/2020 12:32:09
define('MOD_EXTENSION_ENABLED', true);
define('MOD_EXTENSION_TITLE', 'extension LaiKeTui Module');
define('MOD_EXTENSION_VERSION', 1.0);
define('MOD_EXTENSION_NAME', 'extension');
define('MOD_EXTENSION_AUTHOR', 'fly');
define('MOD_EXTENSION_HOMEPAGE', null);
define('MOD_EXTENSION_UPDATE_URL', null);
define('MOD_EXTENSION_DESCRIPTION', 'extension LaiKeTui Module');
?>