<?php
// auth-generated by ModuleConfigHandler
// date: 03/02/2020 12:32:03
define('MOD_NOTICE_ENABLED', true);
define('MOD_NOTICE_TITLE', 'notice LaiKeTui Module');
define('MOD_NOTICE_VERSION', 1.0);
define('MOD_NOTICE_NAME', 'notice');
define('MOD_NOTICE_AUTHOR', 'dhb');
define('MOD_NOTICE_HOMEPAGE', null);
define('MOD_NOTICE_UPDATE_URL', null);
define('MOD_NOTICE_DESCRIPTION', 'notice LaiKeTui Module');
?>